[bugfix]: Increase prefect client timeout
O script que deleta os flows arquivados tá falhando devido ao timeout
de 15 segundos.

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='prefect.basedosdados.org', port=443): Max retries exceeded with url: /api (Caused by ReadTimeoutError("HTTPSConnectionPool(host='prefect.basedosdados.org', port=443): Read timed out. (read timeout=15)"))
```

Vamos aumentar para 60 segundos.

cc @folhesgabriel