[chore]: update manage.py script (#1186)
Relacionado com #1008, último ajuste para fechar #1008.

O script na main está quebrando para alguns comandos:

`uv run manage.py list-projects`: Deveria listar todas as pipelines, mas
mostra apenas isso

```
/home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normaliz
er (2.0.9) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
2025-09-09 10:07:05.965 | INFO     | __main__:list_projects:287 - Projetos cadastrados e nomes reservados:
2025-09-09 10:07:05.965 | INFO     | __main__:list_projects:289 - - constants
2025-09-09 10:07:05.965 | INFO     | __main__:list_projects:289 - - datasets
2025-09-09 10:07:05.965 | INFO     | __main__:list_projects:289 - - flows
2025-09-09 10:07:05.965 | INFO     | __main__:list_projects:289 - - utils
```

`uv run manage.py --help`:

```
/home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.20) or chardet (5.2.0)/charset_normaliz
er (2.0.9) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
                                                                                                                                                                              
 Usage: manage.py [OPTIONS] COMMAND [ARGS]...                                                                                                                                 
                                                                                                                                                                              
╭──────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────╮
│ /home/pedro/Desktop/bd/pipelines/manage.py:293 in <module>                                                                                                                 │
│                                                                                                                                                                            │
│   290                                                                                                                                                                      │
│   291                                                                                                                                                                      │
│   292 if __name__ == "__main__":                                                                                                                                           │
│ ❱ 293 │   app()                                                                                                                                                            │
│   294                                                                                                                                                                      │
│                                                                                                                                                                            │
│ ╭───────────────────────────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────────────────────────╮               │
│ │                        app = <typer.main.Typer object at 0x7fcf9e53b6a0>                                                                                 │               │
│ │        CONSTANTS_FILE_PATH = PosixPath('/home/pedro/Desktop/bd/pipelines/pipelines/constants.py')                                                        │               │
│ │ CONSTANTS_FIND_AGENTS_TEXT = 'M9w=k-b_\n'                                                                                                                │               │
│ │   COOKIECUTTER_PATH_AGENCY = PosixPath('/home/pedro/Desktop/bd/pipelines/pipelines')                                                                     │               │
│ │  COOKIECUTTER_PATH_PROJECT = PosixPath('/home/pedro/Desktop/bd/pipelines/pipelines/{{cookiecutter.project_name}}')                                       │               │
│ │                       exit = <built-in function exit>                                                                                                    │               │
│ │            FLOWS_FILE_PATH = PosixPath('/home/pedro/Desktop/bd/pipelines/pipelines/flows.py')                                                            │               │
│ │                     logger = <loguru.logger handlers=[(id=0, level=10, sink=<stderr>)]>                                                                  │               │
│ │                       path = <module 'posixpath' from '/home/pedro/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/posixpath.py'> │               │
│ │             PIPELINES_PATH = PosixPath('/home/pedro/Desktop/bd/pipelines/pipelines')                                                                     │               │
│ │                    pkgutil = <module 'pkgutil' from '/home/pedro/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/pkgutil.py'>     │               │
│ │                      typer = <module 'typer' from '/home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/__init__.py'>               │               │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯               │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/main.py:340 in __call__                                                                          │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/main.py:323 in __call__                                                                          │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:1442 in __call__                                                                         │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/core.py:740 in main                                                                              │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/core.py:194 in _main                                                                             │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:1186 in make_context                                                                     │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:1786 in parse_args                                                                       │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:1197 in parse_args                                                                       │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:2416 in handle_parse_result                                                              │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:2355 in process_value                                                                    │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/decorators.py:539 in show_help                                                                   │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:730 in get_help                                                                          │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/click/core.py:1064 in get_help                                                                         │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/core.py:754 in format_help                                                                       │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/rich_utils.py:614 in rich_format_help                                                            │
│                                                                                                                                                                            │
│ /home/pedro/Desktop/bd/pipelines/.venv/lib/python3.10/site-packages/typer/rich_utils.py:373 in _print_options_panel                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'
```